wopd_dataset:
  _target_: d123.conversion.datasets.wopd.wopd_converter.WOPDConverter
  _convert_: 'all'

  splits: ["wopd_val"]
  wopd_data_root: "/media/nvme1/waymo_perception" # ${wopd_data_root}
  zero_roll_pitch: true # Whether to zero the roll and pitch of the box detections.
  keep_polar_features: false # Add lidar polar features (range, azimuth, elevation) in addition to XYZ. (slow if true)
  add_map_pose_offset: true # Whether to add the map pose offset to the ego state and box detections.


  dataset_converter_config:
    _target_: d123.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    output_path: ${d123_data_root}
    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Traffic Lights
    include_traffic_lights: false

    # Cameras
    include_cameras: true
    camera_store_option: "binary" # "path", "binary", "mp4"

    # LiDARs
    include_lidars: false
    lidar_store_option: "binary" # "path", "binary"

    # Scenario tag / Route
    # NOTE: These are only supported for nuPlan. Consider removing or expanding support.
    include_scenario_tags: false
    include_route: false
