hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://d123.script.config
    - pkg://d123.script.config.common
    - pkg://d123.script.config.preprocessing
  job:
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths

port_number: 8080
