hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - pkg://py123d.script.config
    - pkg://py123d.script.config.common
  job:
    env_set:
      HYDRA_FULL_ERROR: 1
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths
  - log_writer: arrow_log_writer
  - map_writer: gpkg_map_writer
  - datasets:
      # - nuplan_mini_dataset
      # - carla_dataset
      # - wopd_dataset
      # - av2_sensor_dataset
      - pandaset_dataset
  - _self_


terminate_on_exception: True

force_map_conversion: True
force_log_conversion: True
