_target_: d123.datatypes.scene.scene_filter.SceneFilter
_convert_: 'all'

split_types: null
split_names: ["av2-sensor-mini_train"]
log_names: null


map_names: null
scene_uuids: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null

duration_s: null
history_s: 1.0

camera_types: null

max_num_scenes: null
shuffle: false
