_target_: d123.datatypes.scene.scene_filter.SceneFilter
_convert_: 'all'

split_types: null
split_names:
  - "nuplan_mini_test"
log_names: null


locations: null
scene_uuids:
- "796266a84fd65c71"
- "1ef8b2f08cd65f9a"
- "8922138735b45195"
- "d851006613b85e7b"
- "38ef797d14445e44"
- "a317258b9849542f"
- "83ca370d430e59bc"
- "3159261edbf95519"
- "d3d80c3089905994"
- "8d3b06d2311955cb"
- "1d33208c85c95470"
- "e333523147ba5cc9"
- "94fa6640d9f25c43"
- "0eb46626e2345bae"
- "c20a47af332e58a0"
- "c4153e20ef9f5429"
- "51dc7988d78d545f"
- "7348ea10ac0d58fd"
- "32abded47532514d"
- "4c8bd4c5b1015b82"
- "24334adc21055f43"
- "c1afafec7c1f55c6"
- "61af5c7ad0a75a17"
- "4dc74226975f5060"
- "f3b9c29ceb205216"
- "6fd1090347e05103"
- "8564bae63ebf5e42"
- "4656fe861aed509e"
- "f4aa5f3bf2095608"
- "5dc7c5ab6ad450cb"
- "852e81b1ce2d5ce0"
- "9634e64f32b0584d"
- "765a3a60360950d8"
- "d726695b080d5662"
- "646d3f76770a5159"
- "cc0ba43b91395054"
- "5a30039504185834"
- "396ced8ecffe5d92"
- "2583343f0e095b76"
- "940480c560a459dd"
- "c106ea1d18fa5b46"
- "8a1f92741cf25e94"
- "1e1d33afe06a5dc9"
- "cd1295e8085d5f8a"
- "6c68b2a6d8cc5ea9"
- "be3c5bf59f675e00"
- "053be6c85efa5e17"
- "14756446a3a65d51"
- "f8b10bcaa98a53e8"
- "d72ab3f1878c51a0"
- "0ee073448a2657dc"
- "5726da45814a5649"
- "f8aaded37e735549"
- "c7f921589ed956f3"
- "3852b5feb1215add"
- "fc931d0c156057b5"
- "a8d21fc93a3755c6"
- "3ee7077fadab55aa"
- "5845b5db282858b9"
- "36908fc5872d538d"
- "a075179737ad5140"
- "754820401e085625"
- "469cb3e6d6055f87"
- "230150f0e8ff5d4d"
- "7a8c727978005f14"
- "50038631e81b58c8"
- "b7ca09eed06d5090"
- "780103da783e597b"
- "0c72e0f43f9e5dc5"
- "68ad7730c5885243"
- "2cdec17051d25bb4"
- "fe17bdf412f755e4"
- "53632970c56a5207"
- "6ba4abec7990550c"
- "023028c423715317"
- "963ff52c54685dd3"
- "fdef7ee7067859d3"
- "79d99553e8c15302"
- "e3eaafd948b15069"
- "123dfe0afe85550f"
- "956bfd38d4e75fea"
- "c979bfba27385ba1"
- "74e40b83c2e55f8d"
- "2f6a2c0802b75922"
- "a190fbdd675052e7"
- "4c59ff2f17cd5b12"
- "adb469e65ae256aa"
- "00273245ce175544"
- "49ce38623a9d56fc"
- "e00f8ae7c6fd548e"
- "c525191820d65766"
- "2e190d8d1d435577"
- "2e8e6e5238495570"
- "6629f76b367b5305"
- "de8590ad0fc15d29"
- "f520d009788d5346"
- "e50e1bb8fce354b6"
- "da55b0a04d465781"
- "652ae5b39e575205"
- "2d767bf67a655fb6"

timestamp_threshold_s: null
ego_displacement_minimum_m: null

duration_s: 15.1
history_s: 1.0
