_target_: d123.datatypes.scene.scene_filter.SceneFilter
_convert_: 'all'

split_types: null
split_names: null
log_names: null


map_names: null
scene_tokens: null
timestamp_threshold_s: 10.0
ego_displacement_minimum_m: null

duration_s: 10.0
history_s: 0.0

camera_types: null

max_num_scenes: null
shuffle: True
