hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - pkg://d123.script.config
    - pkg://d123.script.config.common
  job:
    env_set:
      HYDRA_FULL_ERROR: 1
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths
  - log_writer: arrow_log_writer
  - map_writer: gpkg_map_writer
  - datasets:
      # - nuplan_mini_dataset
      # - nuplan_private_dataset
      # - carla_dataset
      - wopd_dataset
      # - av2_sensor_dataset
  - _self_

force_map_conversion: True
force_log_conversion: False
