hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://asim.script.config
    - pkg://asim.script.config.common

  job:
    chdir: False

defaults:
  - default_common
  - default_experiment
  - default_dataset_paths
  - _self_
  - datasets:
    # - nuplan_private_dataset
    - carla_dataset

force_feature_computation: True
