hydra:
  output_subdir: null
  run:
    dir: .
  searchpath:
    - pkg://py123d.script.config
    - pkg://py123d.script.config.common
  job:
    env_set:
      HYDRA_FULL_ERROR: 1
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths
  - log_writer: arrow_log_writer
  - map_writer: arrow_map_writer
  - datasets:
      - av2_sensor_dataset
  - _self_


terminate_on_exception: True

force_map_conversion: True
force_log_conversion: True

pinhole_camera_store_option: "jpeg_binary"  # "path", "jpeg_binary", "png_binary", "mp4"
fisheye_mei_camera_store_option: "jpeg_binary"  # "path", "jpeg_binary", "png_binary", "mp4"
lidar_store_option: "laz_binary"  # "path", "path_merged", "laz_binary", "draco_binary"
