_target_: py123d.datatypes.scene.scene_filter.SceneFilter
_convert_: 'all'

split_types: null
split_names: null
log_names: null


locations: null
scene_uuids: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null

duration_s: 9.2
history_s: 3.0

camera_types: null

max_num_scenes: null
shuffle: false
