_target_: py123d.api.scene.scene_filter.SceneFilter
_convert_: 'all'

datasets: ["kitti360"]
split_types: null
split_names: null
log_names: null


locations: null
scene_uuids: null
timestamp_threshold_s: null

duration_s: null
history_s: null

pinhole_camera_ids: null

max_num_scenes: null
shuffle: False
