_target_: py123d.api.scene.scene_filter.SceneFilter
_convert_: 'all'

split_types: null
split_names:
  - "nuplan_mini_train"
  - "nuplan_mini_val"
  - "nuplan_mini_test"
log_names: null


locations: null
scene_uuids: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
max_num_scenes: null

duration_s: null
history_s: null
