defaults:
  - default_dataset_paths
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# Cache parameters
experiment_name: ???
date_format: '%Y.%m.%d.%H.%M.%S'
experiment_uid: ${now:${date_format}}
output_dir: ${oc.env:D123_EXP_ROOT}/${experiment_name}/${experiment_uid} # path where output csv is saved
