av2-sensor:
  _target_: py123d.conversion.datasets.av2.av2_sensor_converter.AV2SensorConverter
  _convert_: 'all'

  splits: ["av2-sensor_train", "av2-sensor_val", "av2-sensor_test"]
  av2_data_root: ${dataset_paths.av2_data_root}

  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Map
    include_map: true

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Pinhole Cameras
    include_pinhole_cameras: true
    pinhole_camera_store_option: "path" # "path", "jpeg_binary", "png_binary", "mp4"

    # LiDARs
    include_lidars: true
    lidar_store_option: "path_merged"  # "path", "path_merged", "laz_binary", "draco_binary"

    # Not available:
    include_traffic_lights: false
    include_scenario_tags: false
    include_route: false
    include_fisheye_mei_cameras: false
