av2_sensor_dataset:
  _target_: py123d.conversion.datasets.av2.av2_sensor_converter.AV2SensorConverter
  _convert_: 'all'

  splits: ["av2-sensor_train"]
  av2_data_root: ${dataset_paths.av2_data_root}

  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Map
    include_map: true

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Traffic Lights
    include_traffic_lights: false

    # Cameras
    include_cameras: true
    camera_store_option: "binary" # "path", "binary", "mp4"

    # LiDARs
    include_lidars: true
    lidar_store_option: "binary" # "path", "path_merged", "binary"

    # Scenario tag / Route
    # NOTE: These are only supported for nuPlan. Consider removing or expanding support.
    include_scenario_tags: false
    include_route: false
