kitti360_dataset:
  _target_: py123d.conversion.datasets.kitti_360.kitti_360_data_converter.Kitti360DataConverter
  _convert_: 'all'

  splits: ["kitti360"]
  kitti360_data_root: ${dataset_paths.kitti360_data_root}

  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Map
    include_map: true
    
    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Traffic Lights
    include_traffic_lights: false

    # Cameras
    include_cameras: true
    camera_store_option: "path"

    # LiDARs
    include_lidars: true
    lidar_store_option: "path"

    # Scenario tag / Route
    include_scenario_tags: false
    include_route: false
