kitti360_dataset:
  _target_: py123d.conversion.datasets.kitti360.kitti360_converter.Kitti360Converter
  _convert_: 'all'

  splits: ["kitti360_train", "kitti360_val", "kitti360_test"]

  kitti360_data_root: ${dataset_paths.kitti360_data_root}

  # NOTE: We preprocess detections into cache directory to speed up repeated conversions
  # The bounding boxes are preprocessed into a per-frame format based on the ego distance and
  # visibility based on the lidar point cloud.
  detection_cache_root: ${dataset_paths.kitti360_data_root}/preprocessed_detections
  detection_radius: 60.0

  # NOTE:
  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Map
    include_map: true

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Pinhole Cameras
    include_pinhole_cameras: true
    pinhole_camera_store_option: "path" # ${pinhole_camera_store_option} # "path", "jpeg_binary", "png_binary", "mp4"

    # Fisheye Cameras
    include_fisheye_mei_cameras: true
    fisheye_mei_camera_store_option: "path" # ${fisheye_mei_camera_store_option}  # "path", "jpeg_binary", "png_binary", "mp4"

    # LiDARs
    include_lidars: true
    lidar_store_option: "path" # ${lidar_store_option}  # "path", "path_merged", "laz_binary", "draco_binary"

    # Not available:
    include_traffic_lights: false
    include_route: false
    include_scenario_tags: false

  train_sequences: 
    - "2013_05_28_drive_0000_sync"
    - "2013_05_28_drive_0002_sync"
    - "2013_05_28_drive_0003_sync"
    - "2013_05_28_drive_0004_sync"
    - "2013_05_28_drive_0005_sync"
    - "2013_05_28_drive_0006_sync"
    - "2013_05_28_drive_0007_sync"
    - "2013_05_28_drive_0009_sync"
    - "2013_05_28_drive_0010_sync"

  val_sequences: [] 
  test_sequences: []
