nuplan_mini_dataset:
  _target_: py123d.conversion.datasets.nuplan.nuplan_converter.NuPlanConverter
  _convert_: 'all'

  splits: ["nuplan-mini_train", "nuplan-mini_val", "nuplan-mini_test"]
  nuplan_data_root: ${dataset_paths.nuplan_data_root}
  nuplan_maps_root: ${dataset_paths.nuplan_maps_root}
  nuplan_sensor_root: ${dataset_paths.nuplan_sensor_root}

  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Map
    include_map: true

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Traffic Lights
    include_traffic_lights: true

    # Pinhole Cameras
    include_pinhole_cameras: true
    pinhole_camera_store_option: ${pinhole_camera_store_option} # "path", "jpeg_binary", "png_binary", "mp4"

    # LiDARs
    include_lidars: true
    lidar_store_option: ${lidar_store_option} # "path", "path_merged", "laz_binary", "draco_binary"

    # Scenario tag / Route
    include_scenario_tags: true
    include_route: true

    # Not available:
    include_fisheye_mei_cameras: false
