pandaset:
  _target_: py123d.conversion.datasets.pandaset.pandaset_converter.PandasetConverter
  _convert_: 'all'

  splits: ["pandaset_train", "pandaset_val", "pandaset_test"]
  pandaset_data_root: ${dataset_paths.pandaset_data_root}

  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Pinhole Cameras
    include_pinhole_cameras: true
    pinhole_camera_store_option: "path"  # "path", "jpeg_binary", "png_binary", "mp4"

    # LiDARs
    include_lidars: true
    lidar_store_option: "path"  # "path", "path_merged", "laz_binary", "draco_binary"

    # Not available:
    include_map: false
    include_fisheye_mei_cameras: false
    include_traffic_lights: false
    include_scenario_tags: false
    include_route: false


  # NOTE: Pandaset does not have official splits, so we just put all logs in the training set.
  train_log_names:
    - "001"
    - "002"
    - "003"
    - "006"
    - "008"
    - "011"
    - "012"
    - "013"
    - "014"
    - "016"
    - "019"
    - "020"
    - "023"
    - "024"
    - "027"
    - "028"
    - "029"
    - "030"
    - "032"
    - "033"
    - "034"
    - "039"
    - "041"
    - "042"
    - "043"
    - "045"
    - "046"
    - "047"
    - "048"
    - "050"
    - "051"
    - "052"
    - "053"
    - "054"
    - "055"
    - "056"
    - "057"
    - "058"
    - "059"
    - "062"
    - "063"
    - "064"
    - "065"
    - "067"
    - "068"
    - "069"
    - "070"
    - "071"
    - "072"
    - "073"
    - "074"
    - "077"
    - "079"
    - "080"
    - "084"
    - "085"
    - "088"
    - "089"
    - "090"
    - "091"
    - "092"
    - "094"
    - "095"
    - "097"
    - "098"
    - "099"
    - "101"
    - "102"
    - "103"
    - "104"
    - "106"
    - "109"
    - "110"
    - "113"
    - "115"
    - "116"
    - "119"
    - "120"
    - "122"
    - "123"
    - "149"
    - "158"
    - "004"
    - "017"
    - "018"
    - "021"
    - "037"
    - "040"
    - "044"
    - "100"
    - "105"
    - "117"
    - "124"
    - "005"
    - "015"
    - "035"
    - "038"
    - "066"
    - "078"
    - "086"
    - "093"
    - "112"
    - "139"

  val_log_names: []
  test_log_names: []
