wopd_dataset:
  _target_: py123d.conversion.datasets.wopd.wopd_converter.WOPDConverter
  _convert_: 'all'

  splits: ["wopd_val"] # Which splits to convert. Options: ["wopd_train", "wopd_val", "wopd_test"]
  wopd_data_root: "/media/nvme1/waymo_perception" # ${wopd_data_root}
  zero_roll_pitch: true # Whether to zero the roll and pitch of the box detections in global frame.
  keep_polar_features: false # Add lidar polar features (range, azimuth, elevation) in addition to XYZ. (slow if true)
  add_map_pose_offset: true # Whether to add the map pose offset to the ego state and box detections.


  dataset_converter_config:
    _target_: py123d.conversion.dataset_converter_config.DatasetConverterConfig
    _convert_: 'all'

    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}

    # Map
    include_map: true

    # Ego
    include_ego: true

    # Box Detections
    include_box_detections: true

    # Traffic Lights
    include_traffic_lights: false

    # Pinhole Cameras
    include_pinhole_cameras: true
    pinhole_camera_store_option: "binary" # "path", "binary", "mp4"

    # LiDARs
    include_lidars: true
    lidar_store_option: "binary" # "path", "path_merged", "binary"

    # Not available:
    include_scenario_tags: false
    include_route: false
