_target_: d123.common.multithreading.worker_parallel.SingleMachineParallelExecutor
_convert_: 'all'
use_process_pool: True  # If true, use ProcessPoolExecutor as the backend, otherwise uses ThreadPoolExecutor
max_workers: 16        # Number of CPU workers (threads/processes) to use per node, "null" means all available
