_target_: d123.conversion.log_writer.arrow_log_writer.ArrowLogWriter
_convert_: 'all'

compression: null # Compression method for ipc files. Options: None, 'lz4', 'zstd'
compression_level: null # Compression level for ipc files. Options: None, or depending on compression method
