_target_: py123d.conversion.log_writer.arrow_log_writer.ArrowLogWriter
_convert_: 'all'


logs_root: ${dataset_paths.py123d_logs_root}
ipc_compression: null # Compression method for ipc files. Options: None, 'lz4', 'zstd'
ipc_compression_level: null # Compression level for ipc files. Options: None, or depending on compression method
