carla_dataset:
  _target_: d123.dataset.dataset_specific.carla.carla_data_converter.CarlaDataConverter
  _convert_: 'all'

  splits: ["carla"]
  log_path: "${oc.env:HOME}/carla_workspace/data"

  data_converter_config:
    _target_: d123.dataset.dataset_specific.raw_data_converter.DataConverterConfig
    _convert_: 'all'

    output_path: ${d123_data_root}
    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}
    camera_store_option: "path"
    lidar_store_option: "path"
