carla_dataset:
  _target_: d123.dataset.dataset_specific.carla.carla_data_converter.CarlaDataConverter
  _convert_: 'all'

  splits: ["carla"]
  log_path: "${oc.env:HOME}/carla_workspace/data"
  output_path: ${d123_data_root}

  force_log_conversion: True
  force_map_conversion: True
