kitti360_dataset:
  _target_: d123.datasets.kitti_360.kitti_360_data_converter.Kitti360DataConverter
  _convert_: 'all'

  splits: ["kitti360"]
  log_path: ${oc.env:KITTI360_DATA_ROOT}

  data_converter_config:
    _target_: d123.datasets.raw_data_converter.DataConverterConfig
    _convert_: 'all'

    output_path: ${d123_data_root}
    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}
    camera_store_option: "path"
    lidar_store_option: "path"
