nuplan_private_dataset:
  _target_: d123.datasets.nuplan.nuplan_data_converter.NuplanDataConverter
  _convert_: 'all'

  splits: ["nuplan_private_test"]
  log_path: ${oc.env:NUPLAN_DATA_ROOT}/nuplan-v1.1/splits # NOTE: folder including [mini, trainval, test], sometimes not inside "splits" folder

  data_converter_config:
    _target_: d123.datasets.raw_data_converter.DataConverterConfig
    _convert_: 'all'

    output_path: ${d123_data_root}
    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}
    camera_store_option: "binary"
    lidar_store_option: "path"
