nuplan_private_dataset:
  _target_: d123.dataset.dataset_specific.nuplan.nuplan_data_converter.NuplanDataConverter
  _convert_: 'all'

  splits: ["nuplan_private_test"]
  log_path: ${oc.env:NUPLAN_DATA_ROOT}/nuplan-v1.1/splits # NOTE: folder including [mini, trainval, test], sometimes not inside "splits" folder
  sensor_path: ${oc.env:NUPLAN_DATA_ROOT}/nuplan-v1.1/sensor
  output_path: ${d123_data_root}

  force_log_conversion: ${force_log_conversion}
  force_map_conversion: ${force_map_conversion}
