wopd_dataset:
  _target_: d123.dataset.dataset_specific.wopd.wopd_data_converter.WOPDDataConverter
  _convert_: 'all'

  splits: ["wopd_train"]
  log_path: null # TODO: implement

  data_converter_config:
    _target_: d123.dataset.dataset_specific.raw_data_converter.DataConverterConfig
    _convert_: 'all'

    output_path: ${d123_data_root}
    force_log_conversion: ${force_log_conversion}
    force_map_conversion: ${force_map_conversion}
    camera_store_option: "binary"
    lidar_store_option: "binary"
