hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - pkg://d123.script.config
    - pkg://d123.script.config.common
  job:
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths
  - datasets:
    # - nuplan_private_dataset
    # - carla_dataset
    - wopd_dataset
    # - av2_sensor_dataset
<<<<<<< HEAD
    - kitti360_dataset
=======
  - _self_
>>>>>>> dev_v0.0.7

force_map_conversion: False
force_log_conversion: True
