worker:
  _target_: nuplan.planning.utils.multithreading.worker_ray.RayDistributed
  _convert_: all
  master_node_ip: null
  threads_per_node: null
  debug_mode: false
  log_to_driver: true
  logs_subdir: logs
  use_distributed: false
scene_filter:
  _target_: d123.dataset.scene.scene_filter.SceneFilter
  _convert_: all
  split_types: null
  split_names: null
  log_names: null
  map_names: null
  scene_tokens: null
  timestamp_threshold_s: null
  ego_displacement_minimum_m: null
  duration_s: 9.2
  history_s: 3.0
scene_builder:
  _target_: d123.dataset.scene.scene_builder.ArrowSceneBuilder
  _convert_: all
  dataset_path: ${d123_data_root}
distributed_timeout_seconds: 7200
selected_simulation_metrics: null
verbose: false
logger_level: info
logger_format_string: null
max_number_of_workers: null
gpu: true
seed: 42
d123_devkit_root: ${oc.env:D123_DEVKIT_ROOT}
d123_maps_root: ${oc.env:D123_MAPS_ROOT}
d123_data_root: ${oc.env:D123_DATA_ROOT}
nuplan_devkit_root: ${oc.env:NUPLAN_DEVKIT_ROOT}
nuplan_maps_root: ${oc.env:NUPLAN_MAPS_ROOT}
nuplan_data_root: ${oc.env:NUPLAN_DATA_ROOT}
experiment_name: kitti_test2
date_format: '%Y.%m.%d.%H.%M.%S'
experiment_uid: ${now:${date_format}}
output_dir: ${oc.env:D123_EXP_ROOT}/${experiment_name}/${experiment_uid}
force_log_conversion: true
force_map_conversion: false
datasets:
  kitti360_dataset:
    _target_: d123.dataset.dataset_specific.kitti_360.kitti_360_data_converter.Kitti360DataConverter
    _convert_: all
    splits:
    - kitti360
    log_path: ${oc.env:KITTI360_DATA_ROOT}
    data_converter_config:
      _target_: d123.dataset.dataset_specific.raw_data_converter.DataConverterConfig
      _convert_: all
      output_path: ${d123_data_root}
      force_log_conversion: ${force_log_conversion}
      force_map_conversion: ${force_map_conversion}
      camera_store_option: path
      lidar_store_option: path
