# Directory structure
experiment_name: ???
date_format: '%Y.%m.%d.%H.%M.%S'
experiment_uid: ${now:${date_format}}
output_dir: ${oc.env:PY123D_EXP_ROOT}/${experiment_name}/${experiment_uid} # path where output csv is saved

# Logger
logger_level: info
logger_format_string: null
